-- MySQL Script generated by MySQL Workbench
-- Tue Sep 22 19:24:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Mercados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mercados` (
  `couta_over` DOUBLE NOT NULL,
  `cuota_under` DOUBLE NOT NULL,
  `dinero_over` DOUBLE NOT NULL,
  `dinero_under` DOUBLE NOT NULL,
  `tipo_over_under` DOUBLE NOT NULL,
  PRIMARY KEY (`tipo_over_under`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eventos` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `visitante` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `tipo_mercado` DOUBLE NULL,
  `local` VARCHAR(45) NULL,
  PRIMARY KEY (`id_evento`),
 
  CONSTRAINT `tipo_mercado`
    FOREIGN KEY (`tipo_mercado`)
    REFERENCES `mydb`.`Mercados` (`tipo_over_under`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `email_usuarios` VARCHAR(25) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`email_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Apuesta` (
  `tipo_apuesta` VARCHAR(45) NOT NULL,
  `cuota` DOUBLE NOT NULL,
  `dinero` DOUBLE NOT NULL,
  `fecha` DATETIME NOT NULL,
  `Usuarios_email_usuarios` VARCHAR(25) NULL,
  `id_apuesta` INT NOT NULL,
  `tipo_mercado2` DOUBLE NULL,
  
  PRIMARY KEY (`id_apuesta`),
 
  CONSTRAINT `Usuarios_email_usuarios`
    FOREIGN KEY (`Usuarios_email_usuarios`)
    REFERENCES `mydb`.`Usuarios` (`email_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo_mercado2`
    FOREIGN KEY (`tipo_mercado2`)
    REFERENCES `mydb`.`Mercados` (`tipo_over_under`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuenta` (
  `numero_tarjeta` BIGINT(16) NOT NULL,
  `numero_banco` INT NOT NULL,
  `saldo` DOUBLE NOT NULL,
  `Usuarios_email_usuarios` VARCHAR(25) NULL,
  PRIMARY KEY (`numero_tarjeta`),
 
  CONSTRAINT `fk_Cuota_Usuarios1`
    FOREIGN KEY (`Usuarios_email_usuarios`)
    REFERENCES `mydb`.`Usuarios` (`email_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;